#!/bin/sh
# Wrapper for uacme to work on openwrt.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# Initial Author: Toke Høiland-Jørgensen <toke@toke.dk>
# Adapted for uacme: Lucian Cristian <lucian.cristian@gmail.com>
# Adapted for custom CA and TLS-ALPN-01: Peter Putzer <openwrt@mundschenk.at>
# Adapted for dynv6: Christopher Ng <facboy@gmail.com>

SCRIPT_DIR="$(dirname -- $(readlink -f -- "$0"))"

UACME_TMP="/tmp/uacme"

[[ ! -d "${UACME_TMP}" ]] && mkdir "${UACME_TMP}"

run_uacme="${UACME_TMP}/run_uacme.sh"
if [[ ! -e "${run_uacme}" || "${SCRIPT_DIR}/run_uacme.sh.gz" -nt "${run_uacme}" ]]; then
	gunzip -c "${SCRIPT_DIR}/run_uacme.sh.gz" > "${run_uacme}"
fi

exec sh "${run_uacme}" "$@"
